name: Android Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Check Kotlin Lint
        run: ./gradlew ktLintCheck

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble